This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./Thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (122 entries accepted, 0 rejected).
Sorting entries....done (911 comparisons).
Generating output file Thesis.acr....done (62 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
